general:
  buildTool: 'npm'
  inferProjectName: true
  verbose: true

steps:
  cloudFoundryDeploy:
    cloudFoundry:
      org: 'ic-adv-dev-cf'
      space: 'Dev - Team 2218'
      credentialsId: '2218-cf'

stages:
  'Central build':
    buildExecute: true

  'Additional Unit Tests':
    karmaExecuteTests: false

  'Acceptance':
    cloudFoundryDeploy: false

  'Confirm':
    manualConfirmation: false

  'Release':
    cloudFoundryDeploy: true
    tmsUpload: false